# Imagen base de ASP.NET Core 6.0
FROM mcr.microsoft.com/dotnet/aspnet:6.0 AS base
WORKDIR /app
EXPOSE 8080
ENV ASPNETCORE_URLS=http://+:8080

# Imagen SDK para compilar
FROM mcr.microsoft.com/dotnet/sdk:6.0 AS build
WORKDIR /src
COPY ["VelsatMobile/VelsatMobile.csproj", "VelsatMobile/"]
COPY ["VelsatMobile.Data/VelsatMobile.Data.csproj", "VelsatMobile.Data/"]
COPY ["VelsatMobile.Model/VelsatMobile.Model.csproj", "VelsatMobile.Model/"]
RUN dotnet restore "VelsatMobile/VelsatMobile.csproj"
COPY . .
WORKDIR "/src/VelsatMobile"
RUN dotnet build "VelsatMobile.csproj" -c Release -o /app/build

FROM build AS publish
RUN dotnet publish "VelsatMobile.csproj" -c Release -o /app/publish /p:UseAppHost=false

FROM base AS final
WORKDIR /app
COPY --from=publish /app/publish .
ENTRYPOINT ["dotnet", "VelsatMobile.dll"]